### PR TITLE
chore: upgrade project, add Vite, resolve sec advisories

### PR DESCRIPTION
**Pull request by bsmth**
### Description

* align with `npm create vue@latest`
* Upgrade `.nvmrc` to 20
* Bump package to `1.0.0`

### Motivation

There are several security advisories that are not resolvable using `npm audit fix` etc. Additionally, this project should be aligned with the current project configuration when following the official Vue Quickstart.

### Additional details

https://vuejs.org/guide/quick-start.html

### CODE REVIEW

**Comment by bsmth** [comment]
> what issues have not yet been resolved

Thanks for checking. I've marked as ready for review now.

**Comment by queengooborg** [comment]
> @queengooborg - you have some Vue experience, do you spot anything out of place or unusual? 😄

I'm not quite as familiar with Vue + Vite as opposite to just Vue, but it's looking good to me!

**Comment by bsmth** [comment]
> I'm not quite as familiar with Vue + Vite as opposite to just Vue, but it's looking good to me!

Thank you! I think it's in a good state to merge soon 🚢 the corresponding docs PR is approved ✅

**Review by Rumyra — APPROVED** [review]

**Comment by bsmth** [comment]
Thank you!

**Pull request merged**
